define mc = Character("[mc_name]")
define tansy = Character("Tansy")
define clara = Character("Clara")
define tariq = Character("Tariq")
define barek = Character("Barek")
define bao = Character("Bao")
define bruni = Character("Commander Bruni")
define ellie = Character("Ellie")